name: go-cache
on:
  push:
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setuop-go@v2
      with:
        go-version: 1.14

    - name: Check gofmt
      run: test -z "$(gofmt -s -d .)"

    - name: Run go vet
      run: go vet ./...

    - name: Test
      run: go test -v